#        ##################################
#        ## Configuration for PvP Health ##
#        ##################################

useNumericalDisplay: false

halfNumericalDisplay: true
# halfNumericalDisplay: Halves the health sent, such as 4.5 hearts being 4.5/10

hitString: '$9[$6PvP Health$9]$r $b%VICTIM%$c%QUOTE%s health : $6%VICTIM-HEALTH%'
# hitString: The string displayed when the PvP occurred.
#
#    ###################################################
#    #                      Tools                      #
#    ###################################################
#    # %QUOTE% -> '                                    #
#    # $<colour number> - Colour                       #
#    # %VICTIM% - The name of the victim               #
#    # %VICTIM-HEALTH% - The health of the victim      #
#    # %ATTACKER% - The name of the attacker           #
#    # %DAMAGE-DONE% - The damage done by the attacker #
#    ###################################################

preventSpamTime: 2
# preventSpamTime: The time in seconds before another information is sent to the attacker again.
#
# NOTE: Attacks higher than 6 (3 hearts) and victim's health lower than 4 (2 hearts), will bypass this time.

enableHealthtag: true
# enableHealthtag: The (buggy) feature of having health under name tags.