main: com.gmail.chloepika.plugins.pvphealth.PvPHealth
name: PvP Health
version: 1.3
author: Chloe-chan
description: A plugin that shows player's health on attack.

commands:
  health:
    description: PvP Health commands.
    usage: /health help
    aliases: pvphealth